import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Auto-generate sidebar from the docs folder structure
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar configuration for Sonova docs
  /*
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Trading',
      items: ['trading/getting-started', 'trading/advanced-features', 'trading/analytics', 'trading/fees'],
    },
    {
      type: 'category', 
      label: 'Creating',
      items: ['creating/first-collection', 'creating/metadata', 'creating/royalties', 'creating/community'],
    },
    {
      type: 'category',
      label: 'Launchpad',
      items: ['launchpad/overview', 'launchpad/application', 'launchpad/preparation', 'launchpad/configuration', 'launchpad/launch-day'],
    },
    {
      type: 'category',
      label: 'Developers',
      items: ['developers/api-reference', 'developers/js-sdk', 'developers/python-sdk', 'developers/examples', 'developers/webhooks'],
    },
    {
      type: 'category',
      label: 'Help & Support',
      items: ['help/troubleshooting', 'help/faq', 'help/contact'],
    },
  ],
   */
};

export default sidebars;
